---
title: "Resultados preliminares"
format: html
editor: visual
---

```{r}
#| echo: false
# Opciones globales
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)

# Cargar paquetes
pacman::p_load(
  janitor,
  gtsummary,
  scico,
  tidyverse
)
```

## Tablas defunciones por DM

```{r}
# Cargar datos
datos <- read_csv("Bases de datos/defunciones.csv") |> 
  # Ordena datos por provincia y grupo edad
  arrange(prov_res_cat, grupo_edad)
```

### Defunciones por año y provincia

```{r}
datos |> 
 tbl_summary(by = anio,
             include = prov_res_cat) |> 
  add_overall()
```

### Defunciones por sexo y provincia

```{r}
datos |> 
 tbl_summary(by = sexo,
             include = prov_res_cat) |> 
  add_overall()
```

### Defunciones por grupo edad y provincia

```{r}
datos |> 
 tbl_summary(by = prov_res_cat,
             include = grupo_edad) |> 
  add_overall()
```

### Defunciones por sexo y grupo edad (total país)

```{r}
datos |> 
 tbl_summary(by = sexo,
             include = grupo_edad) |> 
  add_overall()
```
